spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb?sslmode=disable
    username: marus
    password: marus
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect




  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false

  security:
    jwt:
      secret: "SuperSecretKeyThatIsLongEnough"
      access-token-expiration-minutes: 15
      refresh-token-expiration-days: 7

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG